var nodes = new vis.DataSet([
    { id: 1, label: "Disconnection", explanation: "To actively change conditions (regarding inequality) it is required for an agent to be a 'problem owner' which causes behavioural change. For this to occur, it is required that the agent is connected to the problem. However, there are indications that portions of the population are disconnected from society causing passive behaviour.",
linkToPageGlobal: 27},
    { id: 2, label: "Democratic Power", explanation: "Democracy is influenced by inequality but the exact mechanism is unclear. Two opposing theorems are the 'redistributive perspective' and the 'unequal power perspective' which state that either democratic power resorts to the median voter or the powerful few respectively.",
linkToPageGlobal: 23},
    { id: 3, label: "Unawareness", explanation: "To create an opinion and consequential policy regarding inequality, it is required to be aware of the (current) situation. However, there are multiple indications that information and policies revolving around inequality are either unknown or misinformation has occurred.",
linkToPageGlobal: 25},
    { id: 4, label: "Stratification", explanation: "Within society, there are population groups which have their specific characterisations. The characteristics cause that they experience different opportunities and effects from policies but also have different behaviour.",
linkToPageGlobal: 35},
    { id: 5, label: "Education", explanation: "Education is a pivotal aspect in the development of human capital of an individual and dictates in large portions the opportunities an individual experiences later in life. When differences occur within the educational system the outcome will experience change.",
linkToPageGlobal: 30},
    { id: 6, label: "Policy Approval", explanation: "To cause change, it is required to enforce policies. The process of how policies are drafted is of large importance to the opportunities to alter the system.",
linkToPageGlobal: 23},
    { id: 7, label: "Measurements", explanation: "To know the present situation and the caused effects of policies it is required to have proper measurements. We find that there are four broad representation methods revolving around inequality: 1. Lorenz-curve based indices, 2. Generalized entropy based indices, 3. Ratio based indices, and 4. Poverty based indices.",
linkToPageGlobal: 55},
    { id: 8, label: "Economic Growth", explanation: "The fortune of society is largely bound by its economic growth, indicating increasing economic opportunities. It is desired for an economy to have high economic growth to spread improving conditions among its population.",
linkToPageGlobal: 38},
    { id: 9, label: "Health", explanation: "One of the most important characteristics for individuals to enjoy life is good health. As such, governments have a duty to attempt to provide good health and improve conditions where possible.",
linkToPageGlobal: 18},
    { id: 10, label: "Opportunity Inequality", explanation: "Economic inequality consists out of three branches, one of them being opportunity inequality. This type of inequality considers the opportunity to change socio-economic position (and tightly related income and wealth characteristics). This type of inequality is related to the human capital one has and can develop.",
linkToPageGlobal: 98},
    { id: 11, label: "Wealth Transfers", explanation: "An important hallmark of wealth is that it can be transferred between individuals. As such, assistance can be given from parent to child, via either in vivo transfers or inheritance, when they require financial funds.",
linkToPageGlobal: 94},
    { id: 12, label: "Mobility", explanation: "Mobility assigns the procedure to move up and down the socio-economic ladder. This can be measured from an inter- and intra-generational perspective, and a relative and an absolute perspective. These differences state whether an individual improves in conditions in absolute terms or relative compared to a point of reference.",
linkToPageGlobal: 99},
    { id: 13, label: "Real Estate", explanation: "An important asset in the portfolio of citizens is real estate. It either is a large portion of their expenses when they are renting or it represents the largest portion of their wealth owned. Either way, it is pivotal in their life and also coordinates inequalities.",
linkToPageGlobal: 98},
    { id: 14, label: "Wealth Inequality", explanation: "Economic inequality consists out of three branches, one of them being wealth inequality. This type of inequality considers all wealth retained by an individual and is intimately connected to the life-cycle of an individual.",
linkToPageGlobal: 93},
    { id: 15, label: "Financialization", explanation: "The economical phenomenon to produce income from trade in financial assets (most often leveraging debt) is called financialization. Since the 1980s this has been an increasingly important pathway to generate income using wealth and has been interacting with the economy.",
linkToPageGlobal: 81},
    { id: 16, label: "Income Inequality", explanation: "Economic inequality consists out of three branches, one of them being income inequality. This type of inequality considers income differences between individuals and is intimately connected to the type of job a person can enrol into.",
linkToPageGlobal: 74},
    { id: 17, label: "Technology", explanation: "Technological changes are an important driver in driving productivity upwards. While doing so, it creates new job opportunities but also causes other jobs to become redundant influencing the jobs market. Moreover, for technological change, R&D investments are required to invent new opportunities.",
linkToPageGlobal: 79},
    { id: 18, label: "Globalization", explanation: "Due to increased connectivity between countries, economies have become increasingly entangled. It has offered an opportunity to produce services & goods in country to the country where it will be consumed. This has notably changed the operations of (multinational) corporations and their supply in the consumption and job market.",
linkToPageGlobal: 79},
    { id: 19, label: "Welfare State", explanation: "A hallmark of Western societies is the welfare state which supports health and social security. As such, it aids the unfortunate who endure problematic situations in life and aims to provide suitable living conditions for all. This guarantee in providing suitable living conditions for all has important consequences from a redistributive perspective.",
linkToPageGlobal: 80},
    { id: 20, label: "Labour Bargaining", explanation: "An important procedure in finding a job and asserting income and other parameters (such as social security) is mediated by labour bargaining. In this process, the labour market clears supply and demand.",
linkToPageGlobal: 83},
    { id: 21, label: "Taxes & Benefits", explanation: "The most important direct policy tool of a government to influence income and wealth (inequalities) is the tax & benefits system. It possesses an opportunity to directly influence  economic processes and alter the income and wealth distribution.",
linkToPageGlobal: 113},
    { id: 22, label: "Undocumented Inequality", explanation: "Measurements will most often run into issues with hiatuses in databases. While some of these hiatuses are accidental, some are deliberate intentions of individuals to decrease the tax base of their income and assets, i.e., tax avoidance and evasion.",
linkToPageGlobal: 48},
    { id: 23, label: "Public Perception", explanation: "To cause change, it is desired that the change is wanted by the public causing that the enforcement of the policy gains less opposition. Moreover, drafting policies can be influenced by the desire of the public to have such a policy enforced. As such, public perception is of large importance to the possible directions of society.",
linkToPageGlobal: 26},
    { id: 24, label: "Data Collection", explanation: "A crucial part to knowing the situation revolving around inequality concerns how data is being collected. Different methods can lead to different outcomes because of their characteristics/ We find that there are three rudimental options to collect data revolving around economic inequality: 1. Tax data, 2. Survey data, and 3. Rich lists.",
linkToPageGlobal: 47},
    { id: 25, label: "Financial Resources", explanation: "It is not always perfectly clear whether wealth or income is having an impact on certain parameters. As a compromise, it has been chosen to use financial resources as an overarching term which integrates both income and wealth when a distinction cannot be made between the parameters.",
linkToPageGlobal: 19},
    { id: 26, label: "Tax Avoidance & Evasion", explanation: "The attempt to reduce tax rate margins is called tax avoidance & evasion. It creates unfairness within the system as the intentions of (governmental) policies cannot be fulfilled. These occurrences can mostly be connected to higher percentiles in the income and wealth distribution because they have more to gain.",
linkToPageGlobal: 49},
    { id: 27, label: "Climate Change",  dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "The emission of greenhouse gases and the consequential climate change have been connected to consumption differences which are connected to inequalities in financial resources. Both on the global as national scale differences can be noted.", linkToPageGlobal: 17, linkToPageNL: 151},
    { id: 28, label: "Crime",  dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "The necessity to engage in malicious behaviour has been connected to the absence of financial resources. For some, it is the last resort to obtain satisfactory living conditions", linkToPageGlobal: 17, linkToPageNL: 151}
]);

var edges = new vis.DataSet([
    { from: 1, to: 2, explanation: "Because of mistrust and disinterest in the political arena, the poor are voting less causing lower democratic power.",
linkToPageGlobal: 27, linkToPageNL: 154 },
    { from: 2, to: 3, explanation: "Because of unawareness of the inequality occurring in society voting is not occurring which favours redistribution.",
linkToPageGlobal: 25, linkToPageNL: 155 },
    { from: 2, to: 4, explanation: "Because of economic immobility stratification occurs causing the possibility for the richest to ascertain their political dominance.",
linkToPageGlobal: 27, linkToPageNL: 156 },
    { from: 2, to: 6, explanation: "Because of democratic power, the rich can favour policy adoption which is in their interest.",
linkToPageGlobal: 28, linkToPageNL: 155 },
    { from: 2, to: 23, explanation: "Because of the public perception, the demands for change in economic inequality can differ as its qualities can be reviewed differently.",
linkToPageGlobal: 26 },
    { from: 2, to: 25, explanation: "Because of economic inequality, the rich can turn economic power into democratic power.",
linkToPageGlobal: 28, linkToPageNL: 156 },
    { from: 3, to: 21, explanation: "There are indications that unawareness exists about specific tax & benefits policies due to the large complexity of the benefits system.",
linkToPageGlobal: 144 },
    { from: 4, to: 5, explanation: "Because of stratification, the potential to gain certain educational outcomes is being prespecified.",
linkToPageGlobal: 34, linkToPageNL: 158 },
    { from: 4, to: 9, explanation: "Because of stratification, differences in health-related behaviour can concentrate among specific strata causing different health-related outcomes.",
linkToPageGlobal: 21, linkToPageNL: 152 },
    { from: 4, to: 10, explanation: "Because of stratification, soft skills and social networks differ leading to opportunity inequality.",
linkToPageGlobal: 38},
    { from: 4, to: 12, explanation: "Segregation of society potentially aids in creating positive/negative effects for social clusters which (negatively) impacts mobility.",
linkToPageGlobal: 98, linkToPageNL: 172 },
    { from: 4, to: 23, explanation: "Because of stratification, the perception of economic inequality can differ as its impact is felt differently.", 
linkToPageGlobal: 100 },
    { from: 5, to: 9, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "Indications are found that education correlates with health due to increased healthy behaviour as a consequence of increased knowledge and higher ability to convert knowledge into behaviour", linkToPageGlobal: 152, linkToPageNL: 152 },
    { from: 5, to: 10, explanation: "Educational differences lead to differences in careers prospects and opportunities to climb the socioeconomic ladder.",
linkToPageGlobal: 33, linkToPageNL: 158 },
    { from: 5, to: 12, explanation: "Mobility is largely enhanced by increased education which enables obtaining a high-wage position and flexibility in the number of job positions available.",
linkToPageGlobal: 32, linkToPageNL: 157 },
    { from: 5, to: 16, explanation: "Because of education, the opportunities to gain certain positions in the job markets are prespecified.",
linkToPageGlobal: 30, linkToPageNL: 158 },
    { from: 6, to: 7, explanation: "It is of core essence to realize that the measurements (and sequential indices) have their specific limitations. It would be ill-advised to devise policies based upon a single index; they should be used coherently.",
linkToPageGlobal: 69, linkToPageNL: 8 },
    { from: 7, to: 22, explanation: "Due to undocumented inequality, there is missing data which leads to incomplete measurements.",
linkToPageGlobal: 48, linkToPageNL: 159 },
    { from: 8, to: 17, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that increased technology increases economic growth by increasing productivity. This interaction has not been reviewed in further detail within this thesis.", linkToPageGlobal: 38, linkToPageNL: 8 },
    { from: 8, to: 25, explanation: "Because the lower portion of the distribution is lacking financial resources to buy goods and services, the economic growth gets hindered due to a loss in demand.",
linkToPageGlobal: 40, linkToPageNL: 159 },
    { from: 9, to: 10, explanation: "Individuals with health-related issues (primarily the poor) have reduced odds in the labour market to acquire work.",
linkToPageGlobal: 19, linkToPageNL: 153 },
    { from: 9, to: 25, explanation: "Because of the lack of financial resources, health-related goods & services cannot be bought causing negative impacts on the poor.",
linkToPageGlobal: 19, linkToPageNL: 152 },
    { from: 10, to: 11, explanation: "The ability to transfer wealth (with low tax rates) causes the ability to transfer socioeconomic position from the parent to the offspring. As such, offspring with rich parents have larger opportunities as compared to their poorer counterparts.",
linkToPageGlobal: 135 },
    { from: 10, to: 25, explanation: "Because of financial resources, it is possible to buy improved educational outcomes causing opportunity inequality.",
linkToPageGlobal: 38,},
    { from: 11, to: 12, explanation: "Mobility is stratified according to wealth transfers, those who receive (in vivo) wealth transfers enable gaining favourable (socio-)economic positions.",
linkToPageGlobal: 94},
    { from: 11, to: 13, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that wealth transfer can aid in the purchase of housing. For example, within the Netherlands there is a dedicated wealth transfer policy.", linkToPageGlobal: 180, linkToPageNL: 180 },
    { from: 11, to: 14, explanation: "Families with wealth are enabled to transfer wealth along sanguine lines which positively correlates with wealth accumulation among recipients. ",
linkToPageGlobal: 94, linkToPageNL: 170 },
    { from: 12, to: 13, explanation: "Mobility is largely stratified according to the lines of real estate ownership having segregation in the household with and without real estate.",
linkToPageGlobal: 98, linkToPageNL: 172 },
    { from: 12, to: 16, explanation: "Inequality and mobility are negatively correlated with each other. Moreover, if there is the fluidity of poor people also being able to become rich at one point in their lives, then inequality would be less of an issue.",
linkToPageGlobal: 100, linkToPageNL: 173 },
    { from: 13, to: 14, explanation: "Wealth inequality runs along with real estate ownership where real estate owners have favourable returns on capital whereas non-real estate owners need to pay (via rent) for living accommodations.",
linkToPageGlobal: 98, linkToPageNL: 171 },
    { from: 13, to: 15, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that increased financialization has entered the real estate market causing an inflationary effect on housing prices.", linkToPageGlobal: 172, linkToPageNL: 172 },
    { from: 14, to: 15, explanation: "The accumulated wealth can be invested into financial assets which have larger returns on investment than saving rents among low-wealth owners causing an increase in inequality.",
linkToPageGlobal: 81, linkToPageNL: 172 },
    { from: 14, to: 16, explanation: "As wealth and income distributions are correlated, the returns from capital are primarily concentrated in the higher income portion of the distribution.",
linkToPageGlobal: 81, linkToPageNL: 169 },
    { from: 14, to: 21, explanation: "The inherent design of the tax systems gives preference for capital income which supports the investment into assets with a (high) return rate. The access to these types of returns is predominantly experienced by the top of the wealth distribution. However, the solution to the inequality is not offered through a recurrent wealth tax but by reducing the income and favourability attached to wealth.",
linkToPageGlobal: 125, linkToPageNL: 178 },
    { from: 14, to: 25, explanation: "Abundance of income enables excess financial resources to be used for other purposes."},
    { from: 15, to: 16, explanation: "Because of financialization, top incomes have various methods to increase their wages using financial assets which are not available to low-wage jobs.",
linkToPageGlobal: 81, linkToPageNL: 165 },
    { from: 15, to: 17, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that increased financialization causes a reduction in investments and as such reduces technological development.", linkToPageGlobal: 159, linkToPageNL: 159 },
    { from: 15, to: 18, explanation: "Because of globalization, it has become possible to transfer wealth across the globe for investment opportunities which can fuel the occurrence of financialization.",
linkToPageGlobal: 80 },
    { from: 16, to: 17, explanation: "Technology increases the capital share from income when mechanization occurs but can also decrease the capital share of income when innovation occurs.",
linkToPageGlobal: 79, linkToPageNL: 166 },
    { from: 16, to: 18, explanation: "Because of globalization, larger opportunities exist for capital to “find” higher returns and labour positions have less bargaining power due to larger competition.",
linkToPageGlobal: 79, linkToPageNL: 166 },
    { from: 16, to: 19, explanation: "Because of the welfare state, institutional designs are possible such as minimum wage which helps in reducing income inequality by aiding low incomes.",
linkToPageGlobal: 80, linkToPageNL: 167 },
    { from: 16, to: 20, explanation: "Because of (increased) labour bargaining, low incomes can obtain higher wages and top income positions are reduced and receive lower wages.",
linkToPageGlobal: 83, linkToPageNL: 167 },
    { from: 16, to: 21, explanation: "The interaction between tax and benefits through means-testing and exemptions and reliefs causes that the bottom deciles experience higher tax rates than the top incomes. As such, relative income redistribution is hampered by the design.",
linkToPageGlobal: 121, linkToPageNL: 175 },
    { from: 16, to: 25, explanation: "Abundance of income enables excess financial resources to be used for other purposes."},
    { from: 18, to: 26, explanation: "Globalization enables wealth (and income) to be hidden from tax agents by using tax heavens.",
linkToPageGlobal: 50},
    { from: 20, to: 21, explanation: "The lower deciles are employed in types of jobs which limit social security and have reduced opportunities in bargaining for favourable incomes. This is in contrast to top incomes who are enabled to bargain for income types with favourable taxation rates.",
linkToPageGlobal: 84, linkToPageNL: 181 },
    { from: 21, to: 22, explanation: "Undocumented inequality leads to wrongfully administered tax rates and supplied benefits.",
linkToPageGlobal: 146, linkToPageNL: 161 },
    { from: 21, to: 23, explanation: "Tax & benefits are importantly connected to the perception of society. While economic theory can direct favourable tax design, society should also accept it to create political momentum to draft its implementation.",
linkToPageGlobal: 148, linkToPageNL: 182 },
    { from: 21, to: 26, explanation: "The various forms of different taxes and a multitude of exemptions and reliefs enable the potential for tax evasion and avoidance. More complex tax design requires higher administration which in turn costs higher work pressure for the administrator. As such, they have less ability to reduce evasion and avoidance as they are experiencing divided attention due to other tasks.",
linkToPageGlobal: 122 },
    { from: 22, to: 24, explanation: "Every type of information source on economic inequality has its limitations in assessing economic inequality. It would be advised to bundle different information sources to limit the amount of undocumented inequality.",
linkToPageGlobal: 47, linkToPageNL: 161 },
    { from: 22, to: 26, explanation: "Tax avoidance & evasion causes that income and wealth are hidden from tax collectors and leads to a hiatus in tax data",
linkToPageGlobal: 50, linkToPageNL: 161 },
    { from: 23, to: 26, explanation: "Depending on the perception of a tax & benefits design, the forcefulness to cohere to its policy will differ. Taxes which are deemed to be “bad” will have more problematic enforcement than those that are perceived as “good”. Similar narratives are warranted for benefits, those that are scrutinized experience a lower willingness to be enrolled for.",
linkToPageGlobal: 122, linkToPageNL: 182 },
    { from: 25, to: 26, explanation: "People with greater wealth or income have improved capabilities to withhold information concerning taxed assets or income.",
linkToPageGlobal: 48, linkToPageNL: 161 },
    { from: 25, to: 27, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that climate change and financial resources are correlated with each other. This is mainly caused by the correlation between financial resources and consumption which leads to higher emissions. However, also the ability to pay for greenhouse-reducing (expensive) goods & services is correlated to the size of financial resources. This interaction has not been investigated to a greater extent due to the scope of the thesis.", linkToPageGlobal: 151, linkToPageNL: 151 },
    { from: 25, to: 28, dashes: true, explanation: "This interaction has not been described during the main review. For further information please visit the analysis of the Netherlands.",
explanationNL: "There are indications that crime and financial resources are correlated with each other. This is mainly caused by the drive to have adequate financial resources to supply proper living conditions. In the absence of these resources, some individuals engage in malicious activities to secure these resources. This interaction has not been investigated to a greater extent due to the scope of the thesis.", linkToPageGlobal: 151, linkToPageNL: 151 },
]);